### PR TITLE
Add cron smoke test

### LINKED ISSUE #13: Introduce cron job smoke test

### PR DESCRIPTION
**Pull request by delucchi-cmu**
Closes #13

### CODE REVIEW

**Comment by smcguire-cmu** [comment]
This is cool. This runs on the main branch, right? I remember there was some discussion about long open pull requests having tests failing after merging due to dependency updates. Do we want to have smoke tests on pull requests as well?

**Comment by delucchi-cmu** [comment]
> This is cool. This runs on the main branch, right? I remember there was some discussion about long open pull requests having tests failing after merging due to dependency updates. Do we want to have smoke tests on pull requests as well?

I don't remember that discussion, but we could consider that option. Do you have some more details?

With a failure on merge, there would at least be some immediate feedback that something was broken. This smoke test is intended to alert folks that something may be broken with a dependency in a project that's not seeing much active development.

**Review by smcguire-cmu — APPROVED** [review]

**Comment by drewoldag** [comment]
The PR that @smcguire-cmu is referring to was a `qp` PR that sat open for a couple weeks before being approved. During that time, the version of one of the dependencies was incremented, and that caused the build to break when _after_ the code was merged into main. 

And, delightfully, made attempts to revert the merge fail as well. :)

It would be cool if we could run cron tests on PRs as well. But at the end of the day, it's probably just better practice to pin dependencies to specific versions.

Which brings up the question, should that be a pre-commit check?

**Comment by drewoldag** [comment]
Also, I don't think that the file needs to have the `.jinja` extension here. That extension is only necessary when `copier` will be going into the file and swapping out a placeholder token with one of the responses to the questions asked when the project was created. I checked the file, and I didn't see any places where that was happening, but perhaps I missed it 🤷

**Comment by smcguire-cmu** [comment]
> The PR that @smcguire-cmu is referring to was a `qp` PR that sat open for a couple weeks before being approved. During that time, the version of one of the dependencies was incremented, and that caused the build to break when _after_ the code was merged into main.
> 
> And, delightfully, made attempts to revert the merge fail as well. :)
> 
> It would be cool if we could run cron tests on PRs as well. But at the end of the day, it's probably just better practice to pin dependencies to specific versions.
> 
> Which brings up the question, should that be a pre-commit check?

I kinda like the idea of pinning dependency versions, but it could lead to issues with conflicting versions if we're writing libraries and our users are trying to use them alongside other libraries. I don't know if this is a done thing or if it's a good idea, but we could have a kind of automated test that excludes specific versions of dependencies if an update causes our code to fail?

It could be nice to have some kind of lock file for dependencies so we can see which versions the code was written using. That's helped me debugging issues from dependency versions in the past. I've used pipenv before which does this, but I don't know if we want to switch to using that since it does python environment managing as well. We could maybe use pip freeze to write our own kind of lock files and have that as a precommit hook, if we want to have something like that?

**Pull request merged**
