### PR TITLE
Put new issues in lincc-frameworks project

### PR DESCRIPTION
**Pull request by drewoldag**
This action should run each time a new issue is created and push it up to the lincc-frameworks project.

### CODE REVIEW

**Review by smcguire-cmu — APPROVED** [review]
lgtm, thanks! This is a cool feature

**Comment by smcguire-cmu** [comment]
Although if we want this to be used by other people we could maybe add a prompt for a project link instead of using our one?

**Comment by drewoldag** [comment]
Good point @smcguire-cmu but this action is meant just for the python-project-template repository. So, it won't be included when someone uses the template for hydrating a project. So _think_ we should be ok on that one.

**Comment by delucchi-cmu** [comment]
But I DOOOO want to use this in other projects. Partiticularly those outside lincc-frameworks organization, where they can't be automatically linked to the project. Let's talk more!

**Pull request merged**
